# Site settings
email: jfthomps@ncsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Apache VCL (Virtual Computing Lab) project
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vcl.apache.org" # the base hostname & protocol for your site
site_title: VCL Documentation
# Build settings
markdown: kramdown

livereload: true

sidebars:

- mydoc_sidebar
